name: Lint Check

on:
  pull_request:
    branches:
        - '*'
        - '!master'
  push:
    branches:
      - master

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install Backend Dependencies
      run: |
        cd back
        npm install
        
    - name: Run ESLint on Backend
      run: |
        cd back
        npx eslint *.js
        if [ $? -eq 0 ]; then
          echo -e "\033[32mSuccess: No ESLint errors found.\033[0m"
        else
          echo -e "\033[31mESLint errors detected.\033[0m"
          exit 1
        fi

    - name: Run Jest Tests
      run: |
        cd back
        npm test

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install Frontend Dependencies
      run: |
        cd front
        npm install
        
    - name: Run ESLint on Frontend
      run: |
        cd front
        npm run lint
        if [ $? -eq 0 ]; then
          echo -e "\033[32mSuccess: No ESLint errors found.\033[0m"
        else
          echo -e "\033[31mESLint errors detected.\033[0m"
          exit 1
        fi
